//! End-to-end feature tests
//!
//! Tests complete language features from source to assembly output

mod aggregate_init;
mod bcd;
mod bcd_validation;
mod bitfields;
mod cmos;
mod complex_features;
mod consts;
mod control_flow;
mod cpu_flags;
mod dead_code;
mod devices;
mod enum_values;
mod enums;
mod error_diagnostics;
mod execution;
mod frames;
mod functions;
mod import_diagnostics;
mod imports;
mod inline;
mod interrupts;
mod interrupts_exec;
mod language_features;
mod local_arrays;
mod loop_sweep;
mod match_ranges;
mod math16;
mod memory;
mod multi_error;
mod operators;
mod org_conflicts;
mod placement;
mod pointer_casts;
mod pointer_escape;
mod pointer_syntax;
mod pointers;
mod spec_examples;
mod statics;
mod stdlib;
mod strings_slices;
mod struct_exprs;
mod temp_pools;
mod types;
mod variables;
mod vtable;
